compressionLevel: mixed

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.0.0.cjs


packageExtensions:
    "local-pkg@*": # This is required for vitest as it accesses happy-dom through local-pkg on its behalf
        dependencies:
            "happy-dom": "*"
    "@testing-library/user-event@*":
        dependencies:
            "@testing-library/dom": "*"